apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azd-kubernetes-manager.fullname" . }}
  labels:
    {{- include "azd-kubernetes-manager.labels" . | nindent 4 }}
data:
  "configuration.yaml": |
    {{- .Values.configuration | toYaml | nindent 4 }}

