{{- if .Values.rbac.psp.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "azd-kubernetes-manager.psp.name" . }}
  labels:
    {{- include "azd-kubernetes-manager.labels" . | nindent 4 }}
    {{- include "azd-kubernetes-manager.stringDict" .Values.rbac.psp.labels | nindent 4 }}
  annotations:
    {{- include "azd-kubernetes-manager.stringDict" .Values.rbac.psp.annotations | nindent 4 }}
    {{- if .Values.rbac.psp.seccompProfile }}
    seccomp.security.alpha.kubernetes.io/allowedProfileNames:  {{ .Values.rbac.psp.seccompProfile | quote }}
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  {{ .Values.rbac.psp.seccompProfile | quote }}
    {{- end }}
    {{- if .Values.rbac.psp.appArmorProfile }}
    apparmor.security.beta.kubernetes.io/allowedProfileNames:  {{ .Values.rbac.psp.appArmorProfile | quote }}
    apparmor.security.beta.kubernetes.io/defaultProfileName:  {{ .Values.rbac.psp.appArmorProfile | quote }}
    {{- end }}
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  requiredDropCapabilities:
  - ALL
  # Allow core volume types.
  volumes:
  - 'configMap'
  - 'secret'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
    # Forbid adding the root group.
    - min: 1
      max: 65535
  readOnlyRootFilesystem: false
{{- end -}}
