{{- if or .Values.rbac.psp.enabled .Values.rbac.psp.name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "azd-kubernetes-manager.psp.rbacname" . }}
  labels:
    {{- include "azd-kubernetes-manager.labels" . | nindent 6 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "azd-kubernetes-manager.psp.rbacname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "azd-kubernetes-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
