{{- if and .Values.username .Values.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azd-kubernetes-manager.fullname" . }}
  labels:
    {{- include "azd-kubernetes-manager.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.username | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}
{{- end }}
