{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azd-kubernetes-manager.fullname" . | quote }}
  labels:
    {{- include "azd-kubernetes-manager.labels" . | nindent 4 }}
{{ end }}
