{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azd-kubernetes-manager.fullname" . | quote }}
  labels:
    {{- include "azd-kubernetes-manager.labels" . | nindent 4 }}
    {{- include "azd-kubernetes-manager.stringDict" .Values.serviceAccount.labels | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- include "azd-kubernetes-manager.stringDict" .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{ end }}
