serviceHooks:
- event: git.pullrequest.updated
  resourceFilters:
    statuses:
    - completed
    - abandoned
    environments:
    - PR
  rules:
    delete:
    - apiVersion: v1
      kind: Namespace
      selector:
        matchLabels:
          azdPullRequestId: '{{ .PullRequestId }}'
        matchExpressions:
        - key: azdPreserve
          operator: DoesNotExist
          values: []
- event: build.complete
  resourceFilters:
    reasons:
    - manual
    environments:
    - PR
  rules:
    delete:
    - apiVersion: v1
      kind: Namespace
      selector:
        matchLabels:
          azdBuildId: '{{ .BuildId }}'
        matchExpressions:
        - key: azdPreserve
          operator: DoesNotExist
          values: []
        - key: azdPullRequestId
          operator: DoesNotExist
          values: []